development:
  store_options:
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

test:
  store_options:
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

production:
  store_options:
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>
